---
matrix:
  ansible: [stable-2.10]
  distro:
    - almalinux/8/cloud
    - amazonlinux/2.0.20210525.0
    - centos/7/cloud
    - debian/11/cloud
    - fedora/34/cloud
    - oracle/8/cloud
    - rockylinux/8/cloud
    - ubuntu/20.04/cloud
  include:
    - ansible: devel
      distro: ubuntu/20.04/cloud
    - ansible: stable-2.9
      distro: centos/7/cloud

adguardhome:
  matrix:
    include:
      - ansible: devel
        distro: ubuntu/20.04/cloud
        install_method: snap
      - ansible: stable-2.9
        distro: ubuntu/18.04/cloud
        install_method: docker

lxd:
  matrix:
    exclude:
      - distro: debian/11/cloud


traefik:
  matrix:
    include:
      ansible: devel
      distro: ubuntu/20.04/cloud
      install_method: docker
