# tasks file for snapd role
---
# See https://forum.snapcraft.io/t/unofficial-snapd-repository-for-amazon-linux-2/24269
# for full information on this.
- name: Add custom snap repo for AWS Linux
  yum_repository:
    name: snapd-amzn2
    description: snapd packages for Amazon Linux 2
    file: snapd-amzn2
    baseurl: 'https://people.canonical.com/~mvo/snapd/amazon-linux2/repo/{{ ansible_machine }}'
    gpgcheck: false
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2"

- name: Install snapd package
  ansible.builtin.package:
    name: snapd
    state: present
    update_cache: true
    enablerepo: "{{ (ansible_distribution == 'CentOS') | ternary('cr,epel', omit) }}"
    disablerepo: "{{ (ansible_distribution == 'Amazon') | ternary('epel', omit) }}"
  tags: snap, snap-install

- name: Install fuse packages to run snaps in virtualized environments
  ansible.builtin.package:
    name: fuse, squashfuse
    state: present
    enablerepo: "{{ (ansible_distribution == 'CentOS') | ternary('epel', omit) }}"
  when:
    - ansible_virtualization_role == "guest"
    - ansible_distribution != "Debian" or ansible_distribution_version | int >= 10
  tags: snap, snap-install

- name: Enable and start snapd socket
  ansible.builtin.systemd:
    name: snapd.socket
    state: started
    enabled: true
  tags: snap, snap-socket

- name: Enable classic snap support on RedHat systems
  ansible.builtin.file:
    path: /snap
    src: /var/lib/snapd/snap
    state: link
  when: ansible_os_family == "RedHat"
  tags: snap, snap-install

- name: Install snap core
  community.general.snap:
    name: core
  register: result
  until: result is not failed
  retries: 3
  tags: snap, snap-install

- name: Install packages from snap
  community.general.snap:
    name: '{{ item.name | default(item) }}'
    channel: '{{ item.channel | default("stable") }}'
    classic: '{{ item.classic | default(false) }}'
  loop: '{{ snap_packages }}'
  when: snap_packages is defined
  tags: snap, snap-packages
