---
dependencies:
  - role: bonddim.linux.epel

galaxy_info:
  description: 'Install snap core and snap packages from https://snapcraft.io/store'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all
  galaxy_tags: []
