---
# tasks file for docker role
- name: Overwrite ansible_os_family for Rocky Linux on ansible < 2.11
  ansible.builtin.set_fact:
    ansible_os_family: 'RedHat'
  when: ansible_os_family == 'Rocky'

- name: Include vars for target host OS
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - 'vars_{{ ansible_distribution }}.yml'
        - 'vars_{{ ansible_os_family }}.yml'
      paths:
        - 'vars'

- name: Remove docker deprecated packages
  ansible.builtin.package:
    name: '{{ docker_deprecated_packages }}'
    state: absent
    purge: '{{ (ansible_os_family == "Debian") | ternary(true, omit) }}'

- name: Include tasks for target host OS
  ansible.builtin.include_tasks:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - 'tasks_{{ ansible_distribution }}.yml'
        - 'tasks_{{ ansible_os_family }}.yml'

- name: Install docker packages
  ansible.builtin.package:
    name: '{{ docker_packages }}'
    state: present
  when: not (ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2')

- name: Ensure docker daemon state
  ansible.builtin.systemd:
    name: docker.service
    state: '{{ docker_daemon_state }}'
    enabled: '{{ docker_daemon_enable }}'

- name: Add user(s) to docker group
  ansible.builtin.user:
    name: '{{ item }}'
    groups: docker
    append: true
  loop: '{{ docker_users }}'

- name: Install docker-compose
  ansible.builtin.include_tasks: compose.yml
  when: docker_compose_install | bool
