---
name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    paths:
      - 'roles/docker/**'
      - 'molecule/docker/**'
      - '.github/workflows/role_docker.yaml'
  pull_request:
    paths:
      - 'roles/docker/**'
      - 'molecule/docker/**'
      - '.github/workflows/role_docker.yaml'

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set build matrix
        id: set-matrix
        uses: bonddim/action-workflow-matrix@v1

  molecule:
    # skip job on pull requests from base repository and tag push
    if: (github.event.pull_request.head.repo.full_name != github.repository) && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: bonddim/action-lxd-init@stable
      - uses: bonddim/action-ansible-molecule@stable
        with:
          molecule-command-args: --scenario-name ${{ github.workflow }}
        env:
          ANSIBLE_VERSION: ${{ matrix.ansible }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
