---
name: users

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    paths:
      - 'roles/users/**'
      - 'molecule/users/**'
      - '.github/workflows/role_users.yaml'
  pull_request:
    paths:
      - 'roles/users/**'
      - 'molecule/users/**'
      - '.github/workflows/role_users.yaml'

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set build matrix
        id: set-matrix
        uses: bonddim/action-workflow-matrix@stable

  molecule:
    # skip job on pull requests from base repository and tag push
    if: (github.event.pull_request.head.repo.full_name != github.repository) && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: matrix
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Run molecule@local
        uses: ./.github/workflows/molecule
